services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./1_label_studio:/label-studio/data
    restart: unless-stopped

  yolo:
    image: ultralytics/ultralytics:latest-arm64
    container_name: yolo-training
    ipc: host
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: sleep infinity
